apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::815388742016:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-26T14:24:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-26T14:24:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1650"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d8b1fd60-3641-49c2-a414-ee1fdb8f4330
